#!/bin/bash
#-------------------------------------------------------------------------------
#
# init_site_admin
#
#-------------------------------------------------------------------------------
# Properties

HELP="
The init_site_admin command initializes the site administration commands so they are easier to use in the system.

Currently the initialization consists of:

1. Adding the site-admin scripts to the current users \$PATH, so we can access them from anywhere without needing to know the location.

2. Setting an optional webmaster email address to be used in all virtual hosts created by this user.

--------------------------------------------------------------------------------

 Developed by Adrian Webb of http://collectivecolors.com
 Licensed under GPL v2

 See the project page at:  http://github.com/collectivecolors/site-admin
 Report issues here:       http://github.com/collectivecolors/site-admin/issues

--------------------------------------------------------------------------------
"

USAGE="
usage: init_site_admin [ --help ]                 # Show usage information
                       ---------------------------------------------------------
                       [ --email <admin-email> ]  # Default administrator email.
"


# Get the directory of this command.

CMD_NAME=`basename $0`
INIT_DIR=`which $CMD_NAME`

if [ ! "$INIT_DIR" ]
then
  CMD_NAME=`readlink -f $0`

  cd `dirname $CMD_NAME`
  INIT_DIR=`pwd`

else
  INIT_DIR=`readlink -f $INIT_DIR`
  INIT_DIR=`dirname $INIT_DIR`
fi

ADMIN_EMAIL=''


# Parse parameters

while test $# -ne 0
do
  case "$1" in

  --help)
    echo "$HELP"
    echo "$USAGE"
    exit 0;;

  --email)
    if [ ! "$2" ]
    then
      echo "Email option requires an email address."
      echo "$USAGE"
      exit 3
    fi

    ADMIN_EMAIL="$2"
    shift;;
  esac
  shift
done


#-------------------------------------------------------------------------------
# Start


if [ "$ADMIN_EMAIL" ]
then
  if ! grep -q "export WEBSERVER_ADMIN_EMAIL=" ~/.profile
  then
    echo "export WEBSERVER_ADMIN_EMAIL=$ADMIN_EMAIL" >> ~/.profile || exit 2
  else
    sed -i "s/WEBSERVER_ADMIN_EMAIL=.*/WEBSERVER_ADMIN_EMAIL=$ADMIN_EMAIL/g" ~/.profile
  fi

  git config --global user.name "$USER@$HOSTNAME"
  git config --global user.email "$ADMIN_EMAIL"
fi


echo "Run: [ source ~/.profile ]"
echo " |"
echo "  \`- to finish the initialization."

